### ISSUE TITLE
[Feature Request] Ability to show percentage completed

### ISSUE THREAD

**Issue by akvabhi** [Dragosarus/Userscripts#2]
Similar to the implementation of remaining time, we can also find out total time ( likely by returning 1st video from getVidNum) and show the percentage completed as well. 
This can be optionally enabled and can be shown like below :
![image](https://user-images.githubusercontent.com/51434019/132137878-2a215401-dd2b-4651-9100-23c74a8b69c2.png)

Also for very large playlists this can be approx percentage.
I think this can provide some moral boost while following some tutorial playlist. 😅

**Comment by Dragosarus** [comment]
I like this idea!

The script has been updated to include this feature (a27259a84291880ac7246779e49f26464b011a78). Enable it by setting `showPercentage = true`.

**Comment by akvabhi** [comment]
Thank you very much. Really amazed to see the quick response.
Definitely a smart move to keep the percentage configurable to show watched/remaining. 👌

BTW couldn't figure why it shows diff of 0.1% on the 1st video.
![image](https://user-images.githubusercontent.com/51434019/132280960-048637d5-cf37-4eec-a525-cfa1116db309.png)
![image](https://user-images.githubusercontent.com/51434019/132281078-3e786dbf-9aeb-4e84-aa7f-95a4c76a02c2.png)

**Comment by Dragosarus** [comment]
It seems I made a few mistakes when calculating the percentage (adeb3304a05a736c0460bdc16df6f0bc16cab73c).
It should now be fixed: 
![drypt_fix_1](https://user-images.githubusercontent.com/66659441/132309309-b9300cf5-2781-4dc9-b266-0a89c4a9218b.PNG)
![drypt_fix_0](https://user-images.githubusercontent.com/66659441/132309481-57f9025c-6115-4a4b-81a1-9e2cb1f750e7.PNG)

**Comment by ghost** [comment]
@Dragosarus can you make them work on invidious too? (youtube makes my pc boom :D)
