### ISSUE TITLE
Playlist reverse makes youtube freeze up when next video is to be autoplayed

### ISSUE THREAD

**Issue by sumsarz** [Dragosarus/Userscripts#3]
And tab closes with a Error code: Out of Memory.

It started happening a few months ago.

Doesn't seem to happen when autoplay is going the normal order.

**Comment by sumsarz** [comment]
Looks to be an infinite loop.

![inf loop](https://user-images.githubusercontent.com/19838146/233799512-20dd5c3d-48d7-42ee-8f04-00eb981225ce.PNG)

**Comment by Dragosarus** [comment]
Thank you for reporting this!
It should be fixed now.
